--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: m7_python_comuna; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.m7_python_comuna (
    cod character varying(5) NOT NULL,
    nombre character varying(255) NOT NULL,
    region_id character varying(2) NOT NULL
);


ALTER TABLE public.m7_python_comuna OWNER TO postgres;

--
-- Name: m7_python_contactform; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.m7_python_contactform (
    id bigint NOT NULL,
    customer_email character varying(254) NOT NULL,
    customer_name character varying(64) NOT NULL,
    message text NOT NULL
);


ALTER TABLE public.m7_python_contactform OWNER TO postgres;

--
-- Name: m7_python_contactform_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.m7_python_contactform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m7_python_contactform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: m7_python_inmueble; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.m7_python_inmueble (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL,
    m2_construidos integer NOT NULL,
    m2_totales integer NOT NULL,
    num_estacionamientos integer NOT NULL,
    num_habitaciones integer NOT NULL,
    "num_baños" integer NOT NULL,
    direccion character varying(255) NOT NULL,
    tipo_inmueble character varying(255) NOT NULL,
    precio integer,
    precio_ufs double precision,
    disponible boolean NOT NULL,
    arrendador_id integer NOT NULL,
    comuna_id character varying(5) NOT NULL
);


ALTER TABLE public.m7_python_inmueble OWNER TO postgres;

--
-- Name: m7_python_inmueble_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.m7_python_inmueble ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m7_python_inmueble_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: m7_python_region; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.m7_python_region (
    cod character varying(2) NOT NULL,
    nombre character varying(255) NOT NULL
);


ALTER TABLE public.m7_python_region OWNER TO postgres;

--
-- Name: m7_python_solicitud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.m7_python_solicitud (
    id bigint NOT NULL,
    fecha timestamp with time zone NOT NULL,
    estado character varying(50) NOT NULL,
    arrendatario_id integer NOT NULL,
    inmueble_id bigint NOT NULL
);


ALTER TABLE public.m7_python_solicitud OWNER TO postgres;

--
-- Name: m7_python_solicitud_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.m7_python_solicitud ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m7_python_solicitud_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: m7_python_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.m7_python_userprofile (
    id bigint NOT NULL,
    rut character varying(9) NOT NULL,
    direccion character varying(255) NOT NULL,
    telefono character varying(255),
    rol character varying(255) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.m7_python_userprofile OWNER TO postgres;

--
-- Name: m7_python_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.m7_python_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m7_python_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add comuna	7	add_comuna
26	Can change comuna	7	change_comuna
27	Can delete comuna	7	delete_comuna
28	Can view comuna	7	view_comuna
29	Can add inmueble	8	add_inmueble
30	Can change inmueble	8	change_inmueble
31	Can delete inmueble	8	delete_inmueble
32	Can view inmueble	8	view_inmueble
33	Can add region	9	add_region
34	Can change region	9	change_region
35	Can delete region	9	delete_region
36	Can view region	9	view_region
37	Can add solicitud	10	add_solicitud
38	Can change solicitud	10	change_solicitud
39	Can delete solicitud	10	delete_solicitud
40	Can view solicitud	10	view_solicitud
41	Can add user profile	11	add_userprofile
42	Can change user profile	11	change_userprofile
43	Can delete user profile	11	delete_userprofile
44	Can view user profile	11	view_userprofile
45	Can add contact form	12	add_contactform
46	Can change contact form	12	change_contactform
47	Can delete contact form	12	delete_contactform
48	Can view contact form	12	view_contactform
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$870000$NFD6idVfdPv8PyuBxDzMoU$5OJ2Y8XpeP1eLSfkOFMpMvfzbspb7wjoVWhUTX9jB/U=	\N	f	edward	Edward	Elrich	edward@mail.com	f	t	2024-09-04 21:10:18.927293-04
3	pbkdf2_sha256$870000$NFD6idVfdPv8PyuBxDzMoU$5OJ2Y8XpeP1eLSfkOFMpMvfzbspb7wjoVWhUTX9jB/U=	\N	f	teresa	Teresa	del Pilar del Sagrado Corazón	teresa@hotmail.com	f	t	2024-09-04 21:10:18.931282-04
4	pbkdf2_sha256$870000$NFD6idVfdPv8PyuBxDzMoU$5OJ2Y8XpeP1eLSfkOFMpMvfzbspb7wjoVWhUTX9jB/U=	\N	f	lenny	Lenny	Kravitz	lenny@gmail.com	f	t	2024-09-04 21:10:18.932279-04
5	pbkdf2_sha256$870000$NFD6idVfdPv8PyuBxDzMoU$5OJ2Y8XpeP1eLSfkOFMpMvfzbspb7wjoVWhUTX9jB/U=	\N	f	pedro	Pedro	Perez	pedro@gmail.com	f	t	2024-09-04 21:10:18.934812-04
8	pbkdf2_sha256$870000$NFD6idVfdPv8PyuBxDzMoU$5OJ2Y8XpeP1eLSfkOFMpMvfzbspb7wjoVWhUTX9jB/U=	\N	f	juana	Juana	Lopendatario	juana@example.com	f	t	2024-09-04 21:10:18.941162-04
1	pbkdf2_sha256$870000$NFD6idVfdPv8PyuBxDzMoU$5OJ2Y8XpeP1eLSfkOFMpMvfzbspb7wjoVWhUTX9jB/U=	2024-09-27 16:10:02.452866-03	f	bruce	Bruce	Dickinson	bruce@gmail.com	f	t	2024-09-04 21:10:18.913173-04
10	pbkdf2_sha256$870000$FfrNDlXTe4VoqCpnzIa3OO$2Pwon/EgTe4FrHOqCZhTzY+QItRJrap7iesZAwDX+a8=	2024-09-24 14:29:54.037208-03	f	tini			tini@gmail.com	f	t	2024-09-24 14:29:52.268722-03
11	pbkdf2_sha256$870000$6OwszKDptdkeX4119KLHdx$yGk4FL8c7KRRJELLETXCD40xBpWKNr/wNtE3V+Qahqs=	2024-09-24 14:59:16.524871-03	f	cami			cami@gmail.com	f	t	2024-09-24 14:59:14.71788-03
12	pbkdf2_sha256$870000$4SAimQnO230P0N3QqmOt7Z$Bv1Kland2SGM6T4+X0p4pJGVAn9moBhyxbBzyLenGmU=	2024-09-24 15:30:14.229898-03	f	ale			ale@gmail.com	f	t	2024-09-24 15:30:12.6686-03
9	pbkdf2_sha256$870000$9rKUR28FZmkqetwN0naBM5$yyEj1SOHs/UU666vZF3DJis8xQWBi70L5lukcd8ebBw=	2024-09-23 19:51:00.094203-03	f	gepe			gepe@gmail.com	f	t	2024-09-23 19:50:57.252564-03
7	pbkdf2_sha256$870000$NFD6idVfdPv8PyuBxDzMoU$5OJ2Y8XpeP1eLSfkOFMpMvfzbspb7wjoVWhUTX9jB/U=	2024-09-27 17:03:35.012302-03	f	toto	Toto	Lopendatario	toto@example.com	f	t	2024-09-04 21:10:18.938171-04
6	pbkdf2_sha256$870000$NFD6idVfdPv8PyuBxDzMoU$5OJ2Y8XpeP1eLSfkOFMpMvfzbspb7wjoVWhUTX9jB/U=	2024-09-25 17:50:25.77128-03	f	manolo	Manolo	Lopendatario	manolo@example.com	f	t	2024-09-04 21:10:18.936172-04
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	m7_python	comuna
8	m7_python	inmueble
9	m7_python	region
10	m7_python	solicitud
11	m7_python	userprofile
12	m7_python	contactform
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2024-09-03 13:22:47.408834-04
2	auth	0001_initial	2024-09-03 13:22:47.559629-04
3	admin	0001_initial	2024-09-03 13:22:47.614998-04
4	admin	0002_logentry_remove_auto_add	2024-09-03 13:22:47.635459-04
5	admin	0003_logentry_add_action_flag_choices	2024-09-03 13:22:47.693963-04
6	contenttypes	0002_remove_content_type_name	2024-09-03 13:22:47.730618-04
7	auth	0002_alter_permission_name_max_length	2024-09-03 13:22:47.745581-04
8	auth	0003_alter_user_email_max_length	2024-09-03 13:22:47.767696-04
9	auth	0004_alter_user_username_opts	2024-09-03 13:22:47.785525-04
10	auth	0005_alter_user_last_login_null	2024-09-03 13:22:47.809403-04
11	auth	0006_require_contenttypes_0002	2024-09-03 13:22:47.814389-04
12	auth	0007_alter_validators_add_error_messages	2024-09-03 13:22:47.822544-04
13	auth	0008_alter_user_username_max_length	2024-09-03 13:22:47.869405-04
14	auth	0009_alter_user_last_name_max_length	2024-09-03 13:22:47.885348-04
15	auth	0010_alter_group_name_max_length	2024-09-03 13:22:47.90575-04
16	auth	0011_update_proxy_permissions	2024-09-03 13:22:47.919465-04
17	auth	0012_alter_user_first_name_max_length	2024-09-03 13:22:47.931433-04
18	sessions	0001_initial	2024-09-03 13:22:47.966522-04
19	m7_python	0001_initial	2024-09-03 20:54:45.936558-04
20	m7_python	0002_contactform	2024-09-24 16:52:00.143284-03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
ch8z339pts758mhs9ds0ri0bvdzn228b	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1ssoEZ:vyjnxNrFMgmdl3vrZo4uA-33yKz0KJlzB_TUwYUm2mI	2024-10-07 15:56:31.196671-03
1fk9iti5ugerwwidd70eg6imdggnau7a	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1ssquY:dpfZ3XTEhqt11ymDwJLgNzTpC5RVPs5ELUjqJ5pFMQ8	2024-10-07 18:48:02.329744-03
6u54djj82gdzhrtb4259iaat3lppqujs	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1ssqwY:kyMWdEnXsBDKkmprju_UJ5aX8HeGXK6Z1QEOB27p6qU	2024-10-07 18:50:06.087844-03
8ki5hbdcls8id0ot3wdazz0k3t13qfze	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1ssqzY:xb3S4fV6edxl2wr9S-2A1vLaPiJwp5aasWyK20oMZoU	2024-10-07 18:53:12.465735-03
dwzxtfidrxyfy4yxepi5rbahtzt9gddm	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1ssr3N:OgNExionUQQsv0Q6eUQ15AieOhcpXPgSc3rY6QD7VJ0	2024-10-07 18:57:09.901384-03
bvlhm27bcdpswne03wtda6gcrjart6b2	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1ssr4Q:3JgkjeNQgQDK4Syeh7Knc5KcO15_xLWWP1ZgGfLVWr8	2024-10-07 18:58:14.533284-03
cpefb0r9h6zkzoimepy1zm7tg5wq0aek	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1ssrBL:iByKtmTEYZeRP_D2ub3w9xKw8R8I4OUuFBXGLJMEBik	2024-10-07 19:05:23.255854-03
qbyihnr0qaywrduzg9lbcat159dphu2g	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1ssrEQ:P7YlqloYW7QHuOfVC6gfflekoiQU8ho2G4OpHk7wacQ	2024-10-07 19:08:34.058805-03
y62f1a0c3k9qib2hluij4037dzi28x1q	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1ssrFr:Od92zIUrAQLFP0QNCuRsk6N28XbiCvFdu6wfm_Lr4S4	2024-10-07 19:10:03.350705-03
sxrtiuj4s6hmoqhr9u3gu10jxdji90zy	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1ssrNf:7vPSwqSltWWmK4MgB97wcleosw7hPGq-_fiR1AX701E	2024-10-07 19:18:07.858892-03
vykkfsdu73stsw8cbgfa6uzawc687t7m	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1ssrgK:Fo6G6jo6Kz6M3FStmLmv2xdHbgodgLXgcAQU3SFJtps	2024-10-07 19:37:24.840923-03
i5tqju3jc5wu4wdoamdw6i4fs4218xy4	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1ssrhQ:TuqevZivCSTuwn-6iSSTjCyTJCuxvVvMmooHj2trbCM	2024-10-07 19:38:32.569518-03
ot6djtf8i4r2497ahlg0dezr0bggu2p0	.eJxVjMsOwiAQAP-FsyFlw6sevfsNZGG3UjWQlPbU-O-WpAe9zkxmFwG3NYet8RJmElcxissvi5heXLqgJ5ZHlamWdZmj7Ik8bZP3Svy-ne3fIGPLfQtx0KDAWu_J0AikDE-Go1PkrWN1rIDIu4GsxxSBXdJ2OnpkZ1CLzxfccDgU:1ssrtU:1TlK53dEzEyBngYsozzND-PIJx1ANJ3zWBVzYUL4soI	2024-10-07 19:51:00.100753-03
p5e4626sgc7wqsnzc8rp27l5l4ocnp2j	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1ssrz4:-53BBOroK7dkKNu-figCIkaEmNaUX5EdAukeRJl-Gq8	2024-10-07 19:56:46.893861-03
jegv2dtkh88u2eyp5r2m49zpg7kulpro	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sss5Z:FKC9A3hSAprkqdYiw7AjXwHJAWd3aClU5ACMg8j76DY	2024-10-07 20:03:29.396478-03
rfz3cserieg4bjw59npbh7t7qeu5ksi7	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sss8h:4_NH5LO0U5_gsv4sJIYMsmhU1wqiia-hlJcCalRW5qM	2024-10-07 20:06:43.45362-03
r5xmhcitj49rsu8pj4dlfekvxhtiw2z9	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sss9n:eCfMQm8bYb8evXMt6a_wMtdyYCA0hDVZC1EllOE8fZ4	2024-10-07 20:07:51.658656-03
q3o3kz9e4aczu4d548pe26dg29knhrda	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sssAz:hMd6HFhbmy99h3sBw5VQgVP8XA-4h7V96CzL6u0qm1s	2024-10-07 20:09:05.172047-03
jq2am45hthn8yq9c5wicxu4uq549zf8g	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sssEv:rcRjq6a4nfhYs9lJBmz8UhO4q3EcgCWxjR3iJyRnbW8	2024-10-07 20:13:09.142536-03
4b7mu0r0vjb9u2moqlxqo0uftxr9salt	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sssgo:0sDjgIreuy3YC48kKbE4jtvD358jecdfici9W6ZBrZ0	2024-10-07 20:41:58.911545-03
z6r8q4qz992iwt4k3iwpim0dgr6bx942	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1ssshu:r7Y96ViyHopKfyAB2Gr9BlUw-vQGm8I3VwWGn7x0ePQ	2024-10-07 20:43:06.388482-03
tjd7eyp7f8rswhfue1xkrmgq5leo3bd9	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sssjD:cjGJhG5LKUecaDSgqOYQnzUhSBs5V0HC_49nqA_CFM8	2024-10-07 20:44:27.230846-03
6wt5a13c0m7j3f4qewkmek3p3dgcbwz0	.eJxVjMsOwiAQRf-FtSE8UgGX7v0GMjAzUjWQlHZl_Hdp0oVu7zn3vEWEbS1x67TEGcVFnMXpd0uQn1R3gA-o9yZzq-syJ7kr8qBd3hrS63q4f4ECvYx3Yj1pa1IgYLZTwKw0BuPJG06kszIMTDmjtca40XXeUXJDB_LKo_h8ARDPOVU:1ssske:NGImPL_irn6p8Me3uPH-9SWFvlQlxnF0Rdw43fcEFf4	2024-10-07 20:45:56.483724-03
txznbfcm60qof3cnqzu1r5fsx0013eul	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sssn1:Qsd4mBnICCogx28c7DMuMKFJMTO0eKrCr15nUcYaopA	2024-10-07 20:48:23.315599-03
lhw5h8zlr47jkgtoou2k5u8if6pjgs12	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sssqe:7LlTiVSnV64EIJiAFh7jHbKsG-ktAbWbuVHqVEBRXrI	2024-10-07 20:52:08.240822-03
b4r2ra72grllr17p3o2vlfwfszr2fstc	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sssrS:ER_4ObfzlQQ-kUdWsFX4lU2VjxKJEAE_Qr-Qsw0dPg4	2024-10-07 20:52:58.071209-03
77rezo95998gfkv7hdg5h9uts3i54bkq	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sssw1:ei9h2wNbkHkvzUAu1vfLm1JppNqugjNoIEt68fYdd7k	2024-10-07 20:57:41.214103-03
ru93xj8rcn67q8j8yfvnto3exs3tkmgj	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1suDPR:YUW44gcUr-OI9bREIwtUOg7GvtJLEo-mpJtAwp4qv4o	2024-10-11 13:01:33.426249-03
1ivv6fsia75wqbieuevj0q3r0hv06rg9	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sstHp:SCPQae4U3X8zARC6wAP-vJPRzOdmyQzDxpoR6y8BczM	2024-10-07 21:20:13.400019-03
hi24gxk8ydi4b4udpiub61el9phtuikw	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1suDVh:mWThUscxZqG6wAgWZdVRN4NgVXaQ-tD50rkZFaBl1kY	2024-10-11 13:08:01.821654-03
othfutshejgho085p54to9rl6by3u5j2	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sstLT:9lSlD7Q7WpQW16r3MniohCmUetqvwENAyJIUyAVrvBQ	2024-10-07 21:23:59.391597-03
1ckqwj5e3zcovk95nqb4dv04dgj9wc62	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1sstPp:nX7YzxNze73aoNT8AajD5iiwX44jOgNPLRkKMLAa8UY	2024-10-07 21:28:29.612286-03
cklwepgxul5n994x4vhbkh79c99q50bh	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1st8Yx:4aE8mIUK3yFH54B-PQ9dB3_hnxjj2-TmvVmJOx6wVvk	2024-10-08 13:38:55.283366-03
kgj62amtxom5yxkcy5kej7krpoy2hruq	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mrcOLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-EWg5Vg:1suHBf:b6wwHeI3b4e3jNJR2g00ROX9OCIulB5g8XG0vdmgOME	2024-10-11 17:03:35.017288-03
houkd2sfopf2ze9pz2ru1nsxnqy25dsl	.eJxVjDsOwyAQBe9CHSE-soCU6XMGtOwuwUkEkrErK3cPllwk7Zt5s4sI21ri1nmJM4mr0OLyuyXAF9cD0BPqo0lsdV3mJA9FnrTLeyN-3073L1Cgl_FOWU_amhQYcrZTIFSagvHsTU6sUZkMmRHJWmPc6DrvOLmhA3vlSXy-DdI5UA:1sthCr:bw0j1prkphWKy7I2ucU0yuc2RoYFNFkVL3sMXUqQ5yY	2024-10-10 02:38:25.928365-03
\.


--
-- Data for Name: m7_python_comuna; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.m7_python_comuna (cod, nombre, region_id) FROM stdin;
01101	Iquique	01
01402	Camiña	01
01403	Colchane	01
01404	Huara	01
01405	Pica	01
01401	Pozo Almonte	01
01107	Alto Hospicio	01
02101	Antofagasta	02
02102	Mejillones	02
02103	Sierra Gorda	02
02104	Taltal	02
02201	Calama	02
02202	Ollagüe	02
02203	San Pedro de Atacama	02
02301	Tocopilla	02
02302	María Elena	02
03101	Copiapó	03
03102	Caldera	03
03103	Tierra Amarilla	03
03201	Chañaral	03
03202	Diego de Almagro	03
03301	Vallenar	03
03302	Alto del Carmen	03
03303	Freirina	03
03304	Huasco	03
04101	La Serena	04
04102	Coquimbo	04
04103	Andacollo	04
04104	La Higuera	04
04105	Paiguano	04
04106	Vicuña	04
04201	Illapel	04
04202	Canela	04
04203	Los Vilos	04
04204	Salamanca	04
04301	Ovalle	04
04302	Combarbalá	04
04303	Monte Patria	04
04304	Punitaqui	04
04305	Río Hurtado	04
05101	Valparaíso	05
05102	Casablanca	05
05103	Concón	05
05104	Juan Fernández	05
05105	Puchuncaví	05
05801	Quilpué	05
05107	Quintero	05
05804	Villa Alemana	05
05109	Viña del Mar	05
05201	Isla de Pascua	05
05301	Los Andes	05
05302	Calle Larga	05
05303	Rinconada	05
05304	San Esteban	05
05401	La Ligua	05
05402	Cabildo	05
05403	Papudo	05
05404	Petorca	05
05405	Zapallar	05
05501	Quillota	05
05502	Calera	05
05503	Hijuelas	05
05504	La Cruz	05
05802	Limache	05
05506	Nogales	05
05803	Olmué	05
05601	San Antonio	05
05602	Algarrobo	05
05603	Cartagena	05
05604	El Quisco	05
05605	El Tabo	05
05606	Santo Domingo	05
05701	San Felipe	05
05702	Catemu	05
05703	Llaillay	05
05704	Panquehue	05
05705	Putaendo	05
05706	Santa María	05
06101	Rancagua	06
06102	Codegua	06
06103	Coinco	06
06104	Coltauco	06
06105	Doñihue	06
06106	Graneros	06
06107	Las Cabras	06
06108	Machalí	06
06109	Malloa	06
06110	Mostazal	06
06111	Olivar	06
06112	Peumo	06
06113	Pichidegua	06
06114	Quinta de Tilcoco	06
06115	Rengo	06
06116	Requínoa	06
06117	San Vicente	06
06201	Pichilemu	06
06202	La Estrella	06
06203	Litueche	06
06204	Marchihue	06
06205	Navidad	06
06206	Paredones	06
06301	San Fernando	06
06302	Chépica	06
06303	Chimbarongo	06
06304	Lolol	06
06305	Nancagua	06
06306	Palmilla	06
06307	Peralillo	06
06308	Placilla	06
06309	Pumanque	06
06310	Santa Cruz	06
07101	Talca	07
07102	Constitución	07
07103	Curepto	07
07104	Empedrado	07
07105	Maule	07
07106	Pelarco	07
07107	Pencahue	07
07108	Río Claro	07
07109	San Clemente	07
07110	San Rafael	07
07201	Cauquenes	07
07202	Chanco	07
07203	Pelluhue	07
07301	Curicó	07
07302	Hualañé	07
07303	Licantén	07
07304	Molina	07
07305	Rauco	07
07306	Romeral	07
07307	Sagrada Familia	07
07308	Teno	07
07309	Vichuquén	07
07401	Linares	07
07402	Colbún	07
07403	Longaví	07
07404	Parral	07
07405	Retiro	07
07406	San Javier	07
07407	Villa Alegre	07
07408	Yerbas Buenas	07
08101	Concepción	08
08102	Coronel	08
08103	Chiguayante	08
08104	Florida	08
08105	Hualqui	08
08106	Lota	08
08107	Penco	08
08108	San Pedro de la Paz	08
08109	Santa Juana	08
08110	Talcahuano	08
08111	Tomé	08
08112	Hualpén	08
08201	Lebu	08
08202	Arauco	08
08203	Cañete	08
08204	Contulmo	08
08205	Curanilahue	08
08206	Los Álamos	08
08207	Tirúa	08
08301	Los Ángeles	08
08302	Antuco	08
08303	Cabrero	08
08304	Laja	08
08305	Mulchén	08
08306	Nacimiento	08
08307	Negrete	08
08308	Quilaco	08
08309	Quilleco	08
08310	San Rosendo	08
08311	Santa Bárbara	08
08312	Tucapel	08
08313	Yumbel	08
08314	Alto Biobío	08
09101	Temuco	09
09102	Carahue	09
09103	Cunco	09
09104	Curarrehue	09
09105	Freire	09
09106	Galvarino	09
09107	Gorbea	09
09108	Lautaro	09
09109	Loncoche	09
09110	Melipeuco	09
09111	Nueva Imperial	09
09112	Padre Las Casas	09
09113	Perquenco	09
09114	Pitrufquén	09
09115	Pucón	09
09116	Saavedra	09
09117	Teodoro Schmidt	09
09118	Toltén	09
09119	Vilcún	09
09120	Villarrica	09
09121	Cholchol	09
09201	Angol	09
09202	Collipulli	09
09203	Curacautín	09
09204	Ercilla	09
09205	Lonquimay	09
09206	Los Sauces	09
09207	Lumaco	09
09208	Purén	09
09209	Renaico	09
09210	Traiguén	09
09211	Victoria	09
10101	Puerto Montt	10
10102	Calbuco	10
10103	Cochamó	10
10104	Fresia	10
10105	Frutillar	10
10106	Los Muermos	10
10107	Llanquihue	10
10108	Maullín	10
10109	Puerto Varas	10
10201	Castro	10
10202	Ancud	10
10203	Chonchi	10
10204	Curaco de Vélez	10
10205	Dalcahue	10
10206	Puqueldón	10
10207	Queilén	10
10208	Quellón	10
10209	Quemchi	10
10210	Quinchao	10
10301	Osorno	10
10302	Puerto Octay	10
10303	Purranque	10
10304	Puyehue	10
10305	Río Negro	10
10306	San Juan de la Costa	10
10307	San Pablo	10
10401	Chaitén	10
10402	Futaleufú	10
10403	Hualaihué	10
10404	Palena	10
11101	Coihaique	11
11102	Lago Verde	11
11201	Aisén	11
11202	Cisnes	11
11203	Guaitecas	11
11301	Cochrane	11
11302	O'Higgins	11
11303	Tortel	11
11401	Chile Chico	11
11402	Río Ibáñez	11
12101	Punta Arenas	12
12102	Laguna Blanca	12
12103	Río Verde	12
12104	San Gregorio	12
12201	Cabo de Hornos	12
12202	Antártica	12
12301	Porvenir	12
12302	Primavera	12
12303	Timaukel	12
12401	Natales	12
12402	Torres del Paine	12
13101	Santiago	13
13102	Cerrillos	13
13103	Cerro Navia	13
13104	Conchalí	13
13105	El Bosque	13
13106	Estación Central	13
13107	Huechuraba	13
13108	Independencia	13
13109	La Cisterna	13
13110	La Florida	13
13111	La Granja	13
13112	La Pintana	13
13113	La Reina	13
13114	Las Condes	13
13115	Lo Barnechea	13
13116	Lo Espejo	13
13117	Lo Prado	13
13118	Macul	13
13119	Maipú	13
13120	Ñuñoa	13
13121	Pedro Aguirre Cerda	13
13122	Peñalolén	13
13123	Providencia	13
13124	Pudahuel	13
13125	Quilicura	13
13126	Quinta Normal	13
13127	Recoleta	13
13128	Renca	13
13129	San Joaquín	13
13130	San Miguel	13
13131	San Ramón	13
13132	Vitacura	13
13201	Puente Alto	13
13202	Pirque	13
13203	San José de Maipo	13
13301	Colina	13
13302	Lampa	13
13303	Tiltil	13
13401	San Bernardo	13
13402	Buin	13
13403	Calera de Tango	13
13404	Paine	13
13501	Melipilla	13
13502	Alhué	13
13503	Curacaví	13
13504	María Pinto	13
13505	San Pedro	13
13601	Talagante	13
13602	El Monte	13
13603	Isla de Maipo	13
13604	Padre Hurtado	13
13605	Peñaflor	13
14101	Valdivia	14
14102	Corral	14
14202	Futrono	14
14201	La Unión	14
14203	Lago Ranco	14
14103	Lanco	14
14104	Los Lagos	14
14105	Máfil	14
14106	Mariquina	14
14107	Paillaco	14
14108	Panguipulli	14
14204	Río Bueno	14
15101	Arica	15
15102	Camarones	15
15201	Putre	15
15202	General Lagos	15
16101	Chillán	16
16102	Bulnes	16
16202	Cobquecura	16
16203	Coelemu	16
16302	Coihueco	16
16103	Chillán Viejo	16
16104	El Carmen	16
16204	Ninhue	16
16303	Ñiquén	16
16105	Pemuco	16
16106	Pinto	16
16205	Portezuelo	16
16107	Quillón	16
16201	Quirihue	16
16206	Ránquil	16
16301	San Carlos	16
16304	San Fabián	16
16108	San Ignacio	16
16305	San Nicolás	16
16207	Treguaco	16
16109	Yungay	16
\.


--
-- Data for Name: m7_python_contactform; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.m7_python_contactform (id, customer_email, customer_name, message) FROM stdin;
1	ale@gmail.com	ale mondaca	hola quiero publicar una vivienda
\.


--
-- Data for Name: m7_python_inmueble; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.m7_python_inmueble (id, nombre, descripcion, m2_construidos, m2_totales, num_estacionamientos, num_habitaciones, "num_baños", direccion, tipo_inmueble, precio, precio_ufs, disponible, arrendador_id, comuna_id) FROM stdin;
2	Departamento Moderno	Departamento céntrico con vista al mar	80	100	1	2	1	Avenida Central 456	departamento	300000	\N	t	4	03102
3	Casa de Playa	Casa frente al mar	150	250	3	3	2	Playa del Sol 789	casa	700000	\N	t	2	04102
4	Loft Urbano	Loft en el corazón de la ciudad	60	80	0	1	1	Calle Urbana 101	departamento	200000	\N	t	4	04301
5	Apartamento Elegante	Apartamento con acabados de lujo	100	120	1	2	2	Avenida Elegancia 222	departamento	400000	\N	t	4	05101
6	Casa Familiar	Amplia casa para toda la familia	180	220	2	5	3	Calle Felicidad 333	casa	600000	\N	t	4	05109
7	Penthouse con Vistas	Penthouse con terraza panorámica	120	150	2	3	2	Avenida Vista 444	parcela	800000	\N	t	3	05403
8	Estudio Acogedor	Estudio ideal para solteros	40	50	0	1	1	Calle Solitaria 555	departamento	150000	\N	t	5	05401
9	Casa Rústica	Casa de campo con chimenea	160	200	1	4	2	Camino Rural 666	casa	550000	\N	t	3	05701
10	Apartamento Minimalista	Apartamento con diseño minimalista	70	90	1	1	1	Avenida Minimal 777	parcela	250000	\N	t	4	05804
11	Casa Tranquila	Casa en zona residencial	140	180	2	4	2	Calle Calma 888	casa	650000	\N	t	2	06202
12	Loft de Diseño	Loft con diseño moderno y elegante	90	110	1	2	1	Calle Diseño 999	departamento	350000	\N	t	5	06303
14	Departamento de Lujo	Departamento en zona exclusiva	110	130	2	3	2	Calle Lujo 1111	departamento	500000	\N	t	1	07304
15	Casa Moderna	Casa con acabados modernos	170	210	2	5	3	Calle Moderna 1212	casa	600000	\N	t	3	07402
16	Departamento Espacioso	Departamento amplio en el centro	120	150	2	3	2	Avenida Espacio 1313	departamento	400000	\N	t	5	08102
17	Casa de Campo	Casa en un entorno rural	150	200	2	4	2	Camino de Campo 1414	casa	550000	\N	t	2	08313
18	Loft de Diseño Industrial	Loft con diseño industrial	100	120	1	2	1	Calle Industrial 1515	departamento	300000	\N	t	4	09115
19	Casa de Verano	Casa para disfrutar el verano	130	180	1	3	2	Playa de Verano 1616	casa	600000	\N	t	5	09207
20	Apartamento Chic	Apartamento con estilo chic	80	100	1	2	1	Calle Chic 1717	departamento	280000	\N	t	1	10301
21	Casona	Es muy amplia	12	4	2	3	1	Las delicias	casa	87000	\N	t	1	02104
13	Casa Contemporánea	Casa con estilo contemporáneo	200	250	2	4	3	Avenida Contemporánea 1000	casa	700000	\N	t	1	07101
1	Casa No Acogedora	Amplia casa con jardín	200	300	2	4	3	Calle Principal 123	casa	500000	\N	f	1	01101
\.


--
-- Data for Name: m7_python_region; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.m7_python_region (cod, nombre) FROM stdin;
01	De Tarapacá
02	De Antofagasta
03	De Atacama
04	De Coquimbo
05	De Valparaíso
06	De O'Higgins
07	Del Maule
08	De Ñuble
09	Del Biobío
10	De La Araucanía
11	De Los Ríos
12	De Los Lagos
13	De Aysén
14	De Magallanes
15	De Arica y Parinacota
16	De Ñuble
\.


--
-- Data for Name: m7_python_solicitud; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.m7_python_solicitud (id, fecha, estado, arrendatario_id, inmueble_id) FROM stdin;
1	2024-09-27 16:54:00.945198-03	pendiente	7	3
\.


--
-- Data for Name: m7_python_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.m7_python_userprofile (id, rut, direccion, telefono, rol, user_id) FROM stdin;
2	123456788	111 Resenvuld	\N	arrendador	2
3	123456787	Lo Pintana 567 psje 1	\N	arrendador	3
4	123456786	Bellavista 914	\N	arrendador	4
5	123456785	Pasaje Volcán Calbuco 123	\N	arrendador	5
6	123456784	Calle Arrendatario 1	\N	arrendatario	6
7	123456783	Calle Arrendatario 2	\N	arrendatario	7
8	123456782	Calle Arrendatario 3	\N	arrendatario	8
16	14758236	alameda 12	96325836	arrendatario	12
1	123456789	Iron Maiden Blvd	\N	arrendador	1
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 12, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: m7_python_contactform_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.m7_python_contactform_id_seq', 1, true);


--
-- Name: m7_python_inmueble_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.m7_python_inmueble_id_seq', 22, true);


--
-- Name: m7_python_solicitud_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.m7_python_solicitud_id_seq', 1, true);


--
-- Name: m7_python_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.m7_python_userprofile_id_seq', 16, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: m7_python_comuna m7_python_comuna_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_comuna
    ADD CONSTRAINT m7_python_comuna_pkey PRIMARY KEY (cod);


--
-- Name: m7_python_contactform m7_python_contactform_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_contactform
    ADD CONSTRAINT m7_python_contactform_pkey PRIMARY KEY (id);


--
-- Name: m7_python_inmueble m7_python_inmueble_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_inmueble
    ADD CONSTRAINT m7_python_inmueble_pkey PRIMARY KEY (id);


--
-- Name: m7_python_region m7_python_region_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_region
    ADD CONSTRAINT m7_python_region_pkey PRIMARY KEY (cod);


--
-- Name: m7_python_solicitud m7_python_solicitud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_solicitud
    ADD CONSTRAINT m7_python_solicitud_pkey PRIMARY KEY (id);


--
-- Name: m7_python_userprofile m7_python_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_userprofile
    ADD CONSTRAINT m7_python_userprofile_pkey PRIMARY KEY (id);


--
-- Name: m7_python_userprofile m7_python_userprofile_rut_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_userprofile
    ADD CONSTRAINT m7_python_userprofile_rut_key UNIQUE (rut);


--
-- Name: m7_python_userprofile m7_python_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_userprofile
    ADD CONSTRAINT m7_python_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: m7_python_comuna_cod_1aaeeec8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX m7_python_comuna_cod_1aaeeec8_like ON public.m7_python_comuna USING btree (cod varchar_pattern_ops);


--
-- Name: m7_python_comuna_region_id_d00fdd4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX m7_python_comuna_region_id_d00fdd4b ON public.m7_python_comuna USING btree (region_id);


--
-- Name: m7_python_comuna_region_id_d00fdd4b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX m7_python_comuna_region_id_d00fdd4b_like ON public.m7_python_comuna USING btree (region_id varchar_pattern_ops);


--
-- Name: m7_python_inmueble_arrendador_id_5081a98a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX m7_python_inmueble_arrendador_id_5081a98a ON public.m7_python_inmueble USING btree (arrendador_id);


--
-- Name: m7_python_inmueble_comuna_id_c49f898b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX m7_python_inmueble_comuna_id_c49f898b ON public.m7_python_inmueble USING btree (comuna_id);


--
-- Name: m7_python_inmueble_comuna_id_c49f898b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX m7_python_inmueble_comuna_id_c49f898b_like ON public.m7_python_inmueble USING btree (comuna_id varchar_pattern_ops);


--
-- Name: m7_python_region_cod_81bd8392_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX m7_python_region_cod_81bd8392_like ON public.m7_python_region USING btree (cod varchar_pattern_ops);


--
-- Name: m7_python_solicitud_arrendatario_id_436d6f89; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX m7_python_solicitud_arrendatario_id_436d6f89 ON public.m7_python_solicitud USING btree (arrendatario_id);


--
-- Name: m7_python_solicitud_inmueble_id_6eb4118a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX m7_python_solicitud_inmueble_id_6eb4118a ON public.m7_python_solicitud USING btree (inmueble_id);


--
-- Name: m7_python_userprofile_rut_fa4cd5e4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX m7_python_userprofile_rut_fa4cd5e4_like ON public.m7_python_userprofile USING btree (rut varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: m7_python_comuna m7_python_comuna_region_id_d00fdd4b_fk_m7_python_region_cod; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_comuna
    ADD CONSTRAINT m7_python_comuna_region_id_d00fdd4b_fk_m7_python_region_cod FOREIGN KEY (region_id) REFERENCES public.m7_python_region(cod) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: m7_python_inmueble m7_python_inmueble_arrendador_id_5081a98a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_inmueble
    ADD CONSTRAINT m7_python_inmueble_arrendador_id_5081a98a_fk_auth_user_id FOREIGN KEY (arrendador_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: m7_python_inmueble m7_python_inmueble_comuna_id_c49f898b_fk_m7_python_comuna_cod; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_inmueble
    ADD CONSTRAINT m7_python_inmueble_comuna_id_c49f898b_fk_m7_python_comuna_cod FOREIGN KEY (comuna_id) REFERENCES public.m7_python_comuna(cod) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: m7_python_solicitud m7_python_solicitud_arrendatario_id_436d6f89_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_solicitud
    ADD CONSTRAINT m7_python_solicitud_arrendatario_id_436d6f89_fk_auth_user_id FOREIGN KEY (arrendatario_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: m7_python_solicitud m7_python_solicitud_inmueble_id_6eb4118a_fk_m7_python; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_solicitud
    ADD CONSTRAINT m7_python_solicitud_inmueble_id_6eb4118a_fk_m7_python FOREIGN KEY (inmueble_id) REFERENCES public.m7_python_inmueble(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: m7_python_userprofile m7_python_userprofile_user_id_bf059ab5_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.m7_python_userprofile
    ADD CONSTRAINT m7_python_userprofile_user_id_bf059ab5_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

